name: Build project and run Lighthouse CI
on: [push, pull_request]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 22.x
      - name: npm install
        run: |
          cd src/tic-tac-toe/
          npm install
      - name: run Lighthouse CI
        run: |
          cd src/tic-tac-toe/
          npm install -g @lhci/cli@0.15.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
